version: '3'



services:
  go:
    build:
      context: .
    container_name: go-gRPC
    tty: true
    volumes:
      - type: bind
        source: ./go
        target: /go/src
    ports:
      - 50051:50051
